apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "magento-test-env.fullname" . }}-elasticsearch
  labels:
    {{- include "magento-test-env.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "magento-test-env.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "magento-test-env.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.10.1
          ports:
            - containerPort: 9200
              name: rest
            - containerPort: 9300
              name: inter-node
          {{- include "magento-test-env.resources" . | nindent 10 }}
          env:
            - name: discovery.type
              value: single-node
